version: "3.9"
services:
  app:
    build: .
    environment: 
      TERM: xterm
    ports:
      - 8000:8000  
      - 35729:35729
      - 1948:1948
      - 1947:1947
    command: npm start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules